import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers";
import NavbarUi from "@/components/navbar/NavbarUi";

export const metadata: Metadata = {
  title: "Amoria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavbarUi />
          <main className="mx-auto p-10 container">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
